name: Build, lint and test
run-name: Build, lint and test triggered by ${{ github.actor }}

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Print information
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Print more information
        run: |
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: "true"

      - name: Print Python version
        run: python --version

      - name: Check lock file consistency
        run: make check-lock-file

      - name: Install the project dependencies
        run: make install-dependencies

      - name: Lint and test code
        run: make clean lint test coverage

      - run: echo "This job's status is ${{ job.status }}."
